### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by manuel-uberti** [manuel-uberti/helm-company#10]
I stopped using Helm months ago, moving to Ivy/Counsel and I'm happy with my current setup. 

I have no plans of going back to Helm so it makes little sense to maintain a fork of a package that works with Helm only. I don't follow Helm development anymore, so I could miss breaking changes or improvements that would need to be reflected on `helm-company`.

If anyone is up for the task, please fork this repository and check with @purcell to update MELPA accordingly.

Thank you.

**Comment by manuel-uberti** [comment]
@melpa is there any chance you could help me spread the word on this?

**Comment by tarsius** [comment]
We could move it to the [Emacsorphanage](https://github.com/emacsorphanage), but not to many people know about that, so that probably wouldn't do much as far as attracting a new maintainer goes.

But maybe @sachac could add a new section to her *Emacs news* posts? Quite a few people read that, I believe.

Anyway, good luck. Finding a successor can take a while:

* https://github.com/flycheck/flycheck/issues/1177
* https://github.com/magit/magit-svn/issues/7
* ...

**Comment by milkypostman** [comment]
could it become part of the helm organization?

**Comment by manuel-uberti** [comment]
Thanks guys. 👍

**Comment by manuel-uberti** [comment]
@thierryvolpiatto could this package become a part of Helm, as @milkypostman suggests?

**Comment by manuel-uberti** [comment]
Yes, sorry, I meant Helm organization as @milkypostman said.

**Comment by Sodel-the-Vociferous** [comment]
@manuel-uberti @thierryvolpiatto Maintaining this package doesn't look too strenuous to me. I'd be happy to take it over.

**Comment by thierryvolpiatto** [comment]
Daniel Ralston <notifications@github.com> writes:

> @manuel-uberti @thierryvolpiatto Maintaining this package doesn't look
> too strenuous to me. I'd be happy to take it over.

You are welcome to maintain it in emacs-helm organization if you want.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Sodel-the-Vociferous** [comment]
I'd like that, thank you!

**Comment by manuel-uberti** [comment]
@Sodel-the-Vociferous thank you very much.

Here's what I think needs to be done:

- fork the repository
- notify @milkypostman and/or @purcell about your fork
- check with them what needs to be done to update MELPA and use your fork as the main repository for `helm-company`

I will link your fork in my README as soon as it is active on MELPA.

Thanks again.

**Comment by purcell** [comment]
Yep, just file a MELPA PR which updates the recipe, and link back to this issue so there's a note of @manuel-uberti signing off on the change of maintainer! :-)

**Comment by manuel-uberti** [comment]
Thanks everybody. I'll close this one and link the new repository in my README.
