### ISSUE TITLE
How to show type information in helm-company?

### ISSUE THREAD

**Issue by tddsg** [manuel-uberti/helm-company#12]
Hi,

When using `company-mode` with C++, I see that type information can be displayed beside function names. However, for `helm-company`, only the function names are displayed. 

So, I'd like to ask how to make `helm-company` display the type information as well?

Thanks!

**Comment by manuel-uberti** [comment]
As specified in the README, this is not the maintained fork anymore. Please open your issue here: https://github.com/Sodel-the-Vociferous/helm-company

**Comment by tddsg** [comment]
Sorry, I was navigated to there from other repository and didn't notice that this one again navigated to the another one
